Hw 14
Lismanuga/Projector-Python pull request #6
Opened 2023-09-09 18:38 UTC by Lismanuga

2023-09-10 12:58 UTC, bielanm requested changes

2023-09-10 12:58 UTC, bielanm commented on HW-14/task3.py
> +        if self.speed >= 5:
якщо швидкість 4, то залишиться 4? може повинна 0 стати?

2023-09-10 15:30 UTC, Lismanuga commented on HW-14/task3.py
> +        if self.speed >= 5:
виправив

2023-09-11 21:59 UTC, bielanm approved these changes

2023-09-11 21:59 UTC, bielanm approved these changes

2023-09-12 08:29 UTC, merged